const data = {
    products:[
        {
            id: '1',
            name: 'Doson',
            brand:'Diptyque',
            price: 230,
            volume: 75,
            image: "images/Doson_img.jpeg",
            scentNotes: ['Floral', 'Citrus', 'Woody'],
        },
        {
            id: '2',
            name: 'Santal 33',
            brand: 'LeLabo',
            price: 322,
            volume: 100,
            image: "images/santal_img.jpeg",
            scentNotes: ['Floral', 'Woody'],
        },
        {
            id: '3',
            name: 'Philosykos',
            brand: 'Diptyque',
            price: 230,
            volume: 75,
            image: 'images/Philosykos.jpeg',
            scentNotes: ['Floral', 'Fruity'],
        },
        {
            id: '4',
            name: 'Baccarat Rouge 540',
            brand: 'Maison Francis Kurkdijan',
            price: 325,
            volume: 71,
            image: 'images/Baccarat_540.jpeg',
            scentNotes: ['Floral', 'Ambery', 'Woody'],
        },
        {
            id: '5',
            name: 'Bergamote 22',
            brand: 'LeLabo',
            price: 322,
            volume: 100,
            image: 'images/Bergamote_img.jpeg',
            scentNotes: ['Floral', 'Citrus', 'Woody'],
        },
        {
            id: '6',
            name: 'Autumn Vibes',
            brand:'Maison Margiela',
            price: 165,
            volume: 100,
            image: 'images/Autumn_vibes_img.jpeg',
            scentNotes: ['Earthy', 'Woody'],
        },
        {
            id: '7',
            name: 'Oud',
            brand: 'Tom Ford',
            price: 445,
            volume: 100,
            image: 'images/Oud_img.jpeg',
            scentNotes: ['Woody', 'Ambery'],
        },
        {
            id: '8',
            name: 'Tam Dao',
            brand: 'Diptyque',
            price: 230,
            volume: 75,
            image: 'images/Tam_dao_img.jpeg',
            scentNotes: ['Powdery','Spicy', 'Woody'],
        },
        {
            id: '9',
            name: 'Bleu de Chanel',
            brand: 'Chanel',
            price: 157,
            volume: 100,
            image: 'images/Blu_de.jpeg',
            scentNotes: ['Ambery', 'Citrus', 'Woody'],
        },
        {
            id: '10',
            name: 'You',
            brand: 'Glossier',
            price: 72,
            volume: 50,
            image: 'images/glossier.jpeg',
            scentNotes: [ 'Iris', 'Powdery', 'Musky'],
        },
        {
            id: '11',
            name: "L'ombre dans l'eau",
            brand: 'Diptyque',
            price: 230,
            volume: 75,
            image: 'images/lombre.jpeg',
            scentNotes: ['Fruity', 'Spicy', 'Woody'],
        },
        {
            id: '12',
            name: 'Kaffir-esque',
            brand: 'Anthropos',
            price: 400,
            volume: 75,
            image: 'images/Kaffir-esque-img.jpeg',
            scentNotes: ['Floral', 'Citrus', 'Woody'],
        },

    ],
};
export default data;